### ISSUE TITLE
GSON module

### ISSUE THREAD

**Issue by Snilonrail** [WaShindeiru/Hyperskill_JSON_Database#3]
https://github.com/WaShindeiru/Hyperskill_JSON_Database/blob/3e48b68837fd5c8f3cbf7b46c52bdd9fe6265908/src/main/java/server/DatabaseFile.java#L3

Just wondering, was it personal decision to use `gson` API or Hyperskill instruction?

**Comment by WaShindeiru** [comment]
Hyperskill strongly encouraged to used gson. It was already included in the project. The same applies to JCommander.
